import React, { useEffect, useRef, useState } from 'react';
import { apiRequest, list, Field, ErrorBox, Badge, PageHead, useData, uploadFile } from './ui.jsx';
import { actionAllowed, createJobActionRunner, createJobRunner, jobState, jobToken } from './job-contract.js';

const arr = value => Array.isArray(value) ? value : (list(value) || []);
const errText = e => e?.message || '请求失败，请稍后重试';
const date = value => value ? new Date(value).toLocaleString() : '—';
function TableState({ loading, error, span }) { if (loading) return <tr><td colSpan={span} className="empty">加载中…</td></tr>; if (error) return <tr><td colSpan={span}><ErrorBox error={errText(error)} /></td></tr>; return null; }

export function AuditPage() {
  const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null),[filters,setFilters]=useState({action:'',resource_type:'',actor:'',resource_id:'',success:''});
  const load=async()=>{setLoading(true);setError(null);try{const q=new URLSearchParams({limit:'100'});Object.entries(filters).forEach(([k,v])=>v&&q.set(k,v));setRows(arr(await apiRequest(`/audit?${q}`)))}catch(e){setError(e)}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  return <div className="page"><PageHead eyebrow="系统管理" title="审计中心" desc="按操作者、资源和动作检索审计记录。"/><div className="toolbar">{Object.keys(filters).slice(0,4).map(k=><input key={k} className="search small" placeholder={k} value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}/>)}<select value={filters.success} onChange={e=>setFilters({...filters,success:e.target.value})}><option value="">全部结果</option><option value="true">成功</option><option value="false">失败</option></select><button className="btn primary" onClick={()=>{void load()}}>查询</button></div><section className="card"><div className="table-wrap"><table><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>资源</th><th>结果</th><th>详情</th></tr></thead><tbody><TableState loading={loading} error={error} span="6"/>{!loading&&!error&&!rows.length&&<tr><td colSpan="6" className="empty">暂无审计记录</td></tr>}{!loading&&!error&&rows.map((r,i)=><tr key={r.id||i}><td>{date(r.created_at)}</td><td>{r.actor||'—'}</td><td className="mono">{r.action||'—'}</td><td className="mono">{r.resource_type||'—'}<br/>{r.resource_id||'—'}</td><td><Badge tone={r.success===false?'red':'green'}>{r.success===false?'失败':'成功'}</Badge></td><td className="mono">{r.details?JSON.stringify(r.details):'—'}</td></tr>)}</tbody></table></div></section></div>;
}

function CategoryTable({rows,refresh}) { const [edit,setEdit]=useState(null),[error,setError]=useState(null); const save=async()=>{try{const {id,code,parent_code,parent_name,is_leaf,...body}=edit;if(id)await apiRequest(`/categories/${id}`,{method:'PATCH',body});else await apiRequest('/categories',{method:'POST',body});setEdit(null);refresh()}catch(e){setError(e)}};const toggle=async r=>{try{await apiRequest(`/categories/${r.id}`,{method:'PATCH',body:{is_enabled:!r.is_enabled}});refresh()}catch(e){setError(e)}};return <>{error&&<ErrorBox error={errText(error)}/>} {edit&&<section className="card form-card"><div className="form-grid"><Field label="大类编码"><input maxLength="2" value={edit.major_code||''} onChange={e=>setEdit({...edit,major_code:e.target.value.replace(/\D/g,'').slice(0,2)})}/></Field><Field label="小类编码"><input maxLength="2" value={edit.minor_code||''} onChange={e=>setEdit({...edit,minor_code:e.target.value.replace(/\D/g,'').slice(0,2)})}/></Field><Field label="名称"><input required value={edit.name||''} onChange={e=>setEdit({...edit,name:e.target.value})}/></Field><Field label="大类名称"><input value={edit.major_name||''} onChange={e=>setEdit({...edit,major_name:e.target.value})}/></Field><Field label="描述" wide><textarea value={edit.description||''} onChange={e=>setEdit({...edit,description:e.target.value})}/></Field><div className="form-actions"><span/><div><button className="btn primary" disabled={edit.major_code?.length!==2||edit.minor_code?.length!==2||!edit.name} onClick={()=>{void save()}}>保存</button><button className="btn ghost" onClick={()=>setEdit(null)}>取消</button></div></div></div></section>}<section className="card"><div className="card-head"><h2>分类目录</h2><button className="btn primary tiny" onClick={()=>setEdit({major_code:'',minor_code:'',name:'',major_name:'',description:'',is_enabled:true})}>新增分类</button></div><table><thead><tr><th>编码</th><th>大类</th><th>小类</th><th>名称</th><th>状态</th><th>操作</th></tr></thead><tbody>{!rows.length&&<tr><td colSpan="6" className="empty">暂无分类</td></tr>}{rows.map(r=><tr key={r.id}><td className="mono">{r.code||`${r.major_code}${r.minor_code}`}</td><td>{r.major_name||'—'}</td><td>{r.minor_code||'—'}</td><td>{r.name}</td><td><Badge tone={r.is_enabled===false?'gray':'green'}>{r.is_enabled===false?'已停用':'启用'}</Badge></td><td><button className="row-action" onClick={()=>setEdit(r)}>编辑</button> <button className="row-action" onClick={()=>{void toggle(r)}}>{r.is_enabled===false?'启用':'停用'}</button></td></tr>)}</tbody></table></section></> }
function UnitTable({rows,refresh}) { const [edit,setEdit]=useState(null),[error,setError]=useState(null);const save=async()=>{try{const {id,...body}=edit;if(id)await apiRequest(`/units/${id}`,{method:'PATCH',body});else await apiRequest('/units',{method:'POST',body});setEdit(null);refresh()}catch(e){setError(e)}};const remove=async id=>{if(!window.confirm('确认删除该单位？'))return;try{await apiRequest(`/units/${id}`,{method:'DELETE'});refresh()}catch(e){setError(e)}};return <>{error&&<ErrorBox error={errText(error)}/>} {edit&&<section className="card form-card"><div className="form-grid"><Field label="编码"><input value={edit.code||''} onChange={e=>setEdit({...edit,code:e.target.value})}/></Field><Field label="名称"><input value={edit.name||''} onChange={e=>setEdit({...edit,name:e.target.value})}/></Field><Field label="维度"><input value={edit.dimension||'each'} onChange={e=>setEdit({...edit,dimension:e.target.value})}/></Field><div className="form-actions"><span/><div><button className="btn primary" onClick={()=>{void save()}}>保存</button><button className="btn ghost" onClick={()=>setEdit(null)}>取消</button></div></div></div></section>}<section className="card"><div className="card-head"><h2>计量单位</h2><button className="btn primary tiny" onClick={()=>setEdit({code:'',name:'',dimension:'each'})}>新增单位</button></div><table><thead><tr><th>编码</th><th>名称</th><th>维度</th><th>操作</th></tr></thead><tbody>{!rows.length&&<tr><td colSpan="4" className="empty">暂无单位</td></tr>}{rows.map(r=><tr key={r.id}><td className="mono">{r.code}</td><td>{r.name}</td><td>{r.dimension||'—'}</td><td><button className="row-action" onClick={()=>setEdit(r)}>编辑</button> <button className="row-action" onClick={()=>{void remove(r.id)}}>删除</button></td></tr>)}</tbody></table></section></> }
function UsersTable(){const [data,setData]=useState(null),[error,setError]=useState(null),[busy,setBusy]=useState('');const load=async()=>{try{setData(await apiRequest('/auth/users'))}catch(e){setError(e)}};useEffect(()=>{void load()},[]);const change=async(username,role,action='assign_role')=>{setBusy(username+action);setError(null);try{await apiRequest('/auth/users',{method:'POST',body:{username,role,action}});await load()}catch(e){setError(e)}finally{setBusy('')}};if(!data)return <section className="card"><p className="muted">加载用户与角色…</p>{error&&<ErrorBox error={errText(error)}/>}</section>;return <section className="card"><div className="card-head"><div><h2>LDAP 用户与本地角色</h2><span className="muted">LDAP 只负责登录；角色、停用和撤权只写入 PLM 数据库。</span></div><button className="btn secondary tiny" onClick={()=>{void load()}}>刷新</button></div>{error&&<ErrorBox error={errText(error)}/>}<div className="table-wrap"><table><thead><tr><th>账号</th><th>状态</th><th>本地角色</th><th>操作</th></tr></thead><tbody>{(data.users||[]).map(u=><tr key={u.username}><td className="mono">{u.username}</td><td><Badge tone={u.active?'green':'gray'}>{u.active?'启用':'已停用'}</Badge></td><td>{u.role?roleLabel(u.role):<span className="muted">待分配</span>}</td><td><select value={u.role||''} disabled={busy===u.username+'assign_role'} onChange={e=>e.target.value&&void change(u.username,e.target.value)}><option value="">分配角色…</option>{(data.roles||[]).map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select>{u.active?<button className="row-action" disabled={busy===u.username+'disable'} onClick={()=>void change(u.username,u.role||'viewer','disable')}>停用</button>:<button className="row-action" onClick={()=>void change(u.username,u.role||'viewer','enable')}>启用</button>}{u.role&&<button className="row-action" onClick={()=>void change(u.username,u.role,'revoke')}>撤权</button>}</td></tr>)}</tbody></table></div></section>}
const roleLabel=r=>({viewer:'查看者',engineer:'工程师',reviewer:'审核员',publisher:'发布员',auditor:'审计员',sysadmin:'系统管理员',admin:'管理员'}[r]||r);
export function AdminPage(){const [tab,setTab]=useState('categories'),[refresh,setRefresh]=useState(0);const cats=useData('/categories',refresh),units=useData('/units',refresh);const bump=()=>setRefresh(v=>v+1);return <div className="page"><PageHead eyebrow="系统管理" title="管理中心" desc="维护分类、计量单位和本地用户权限。"/><div className="tabs"><button className={tab==='categories'?'active':''} onClick={()=>setTab('categories')}>零件分类</button><button className={tab==='units'?'active':''} onClick={()=>setTab('units')}>计量单位</button><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>用户与角色</button></div>{tab==='categories'?<CategoryTable rows={arr(cats.data)} refresh={bump}/>:tab==='units'?<UnitTable rows={arr(units.data)} refresh={bump}/>:<UsersTable/>}</div>}

const stateLabel = state => ({awaiting_confirmation:'待确认',completed_with_errors:'完成但有错误',dry_run:'预检完成',committing:'提交中',queued:'排队中',running:'执行中',completed:'已完成',failed:'失败',cancelled:'已取消',expired:'已过期',staged:'待确认'}[state] || state);
const stateTone = state => state==='completed'?'green':(['failed','completed_with_errors'].includes(state)?'red':(['queued','running','processing','dry_run','awaiting_confirmation','staged','committing'].includes(state)?'amber':'blue'));

export function JobsPage({user}){
 const canWrite=['engineer','admin'].includes(user?.role),canExport=['viewer','engineer','reviewer','publisher','admin'].includes(user?.role);
 const [jobs,setJobs]=useState([]),[exports,setExports]=useState([]),[kind,setKind]=useState('part'),[format,setFormat]=useState('csv'),[file,setFile]=useState(null),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[actionBusy,setActionBusy]=useState(false),[refreshing,setRefreshing]=useState(false),[error,setError]=useState(null);
 const [runJobAction]=useState(()=>createJobActionRunner(apiRequest));
 const [runJobCreate]=useState(()=>createJobRunner(apiRequest));
 const actionRunning=useRef(false),importRunning=useRef(false),exportRunning=useRef(false);
 const load=async({silent=false}={})=>{if(!silent)setRefreshing(true);try{const [i,e]=await Promise.all([apiRequest('/jobs?kind=import'),apiRequest('/jobs?kind=export')]);let imports=arr(i),exportsRows=arr(e);const candidates=imports.filter(j=>j.id&&!jobToken(j)&&['awaiting_confirmation','dry_run','staged'].includes(jobState(j)));if(candidates.length){const details=await Promise.allSettled(candidates.map(j=>apiRequest(`/jobs/${j.id}`)));imports=imports.map(j=>{const at=candidates.findIndex(x=>x.id===j.id),d=at>=0?details[at]:null;return d?.status==='fulfilled'?{...j,...d.value}:j})}setJobs(imports);setExports(exportsRows);setError(null)}catch(e){setError(e)}finally{if(!silent)setRefreshing(false)}};
 useEffect(()=>{void load();const timer=setInterval(()=>{void load({silent:true})},5000);return()=>clearInterval(timer)},[]);
 const action=async(job,name)=>{if(actionRunning.current||busy)return;actionRunning.current=true;setActionBusy(true);setError(null);try{await runJobAction(job,name);await load()}catch(e){setError(e)}finally{actionRunning.current=false;setActionBusy(false)}};
 const upload=async()=>{if(!file||busy||importRunning.current)return;importRunning.current=true;setBusy(true);setError(null);try{const s=await uploadFile(file,setProgress,undefined,'import_source');await runJobCreate(`import:${s.id}`,'/imports',{method:'POST',body:{kind,upload_session:s.id}});setFile(null);await load()}catch(e){setError(e)}finally{importRunning.current=false;setBusy(false)}};
 const createExport=async()=>{if(refreshing||exportRunning.current)return;exportRunning.current=true;setError(null);try{await runJobCreate(`export:${kind}:${format}`,'/exports',{method:'POST',body:{kind,format,filters:{}}});await load()}catch(e){setError(e)}finally{exportRunning.current=false}};
 const downloadArtifact=async job=>{setError(null);try{const r=await apiRequest(`/exports/${job.id}/download`);const url=r?.url||r?.download_url;if(url)window.open(url,'_blank','noopener,noreferrer')}catch(e){setError(e)}};
 const downloadErrors=async job=>{setError(null);try{const r=await apiRequest(`/jobs/${job.id}/errors`),url=r?.url||r?.download_url;if(url){window.open(url,'_blank','noopener,noreferrer');return}const blob=new Blob([JSON.stringify(r,null,2)],{type:'application/json;charset=utf-8'}),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=`job-${job.id}-errors.json`;a.click();URL.revokeObjectURL(href)}catch(e){setError(e)}};
 const renderActions=job=>{const state=jobState(job),token=jobToken(job),canAct=canWrite||(job.job_type==='export'&&['viewer','engineer','reviewer','publisher','admin'].includes(user?.role));return <>{canAct&&actionAllowed(job,'commit')&&<button type="button" className="row-action" disabled={!token||busy||actionBusy} onClick={()=>{void action(job,'commit')}}>确认提交</button>}{canAct&&actionAllowed(job,'cancel')&&<button type="button" className="row-action" disabled={busy||actionBusy} onClick={()=>{void action(job,'cancel')}}>取消</button>}{canAct&&actionAllowed(job,'retry')&&<button type="button" className="row-action" disabled={busy||actionBusy} onClick={()=>{void action(job,'retry')}}>重试</button>}{(Number(job.error_count||job.summary?.error_count||0)>0||['failed','completed_with_errors'].includes(state))&&<button type="button" className="row-action" disabled={actionBusy} onClick={()=>{void downloadErrors(job)}}>错误报告</button>}</>};
 const importSummary=j=>{const s=j.summary||{};return `${s.created||s.valid||0} 新增 / ${s.error_count||j.error_count||0} 错误`};
 return <div className="page"><PageHead eyebrow="文件中心" title="导入导出任务" desc="CSV/JSON 先直传 MinIO，再由 Worker 预检和提交。结构化导入上限 5 MiB。"/>{error&&<ErrorBox error={errText(error)}/>} {canWrite&&<section className="card"><div className="form-grid"><Field label="数据类型"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="category">分类</option><option value="part">零件</option><option value="bom">BOM</option></select></Field><Field label="文件"><input type="file" accept=".csv,.json" onChange={e=>setFile(e.target.files?.[0]||null)}/><small>最大 5 MiB，直接上传 MinIO</small></Field></div><div className="form-actions"><span className="muted">{busy?`上传 ${progress}%`:file?.name||'未选择文件'}</span><button type="button" className="btn primary" disabled={!file||busy} onClick={()=>{void upload()}}>上传并预检</button></div></section>}<section className="card"><div className="card-head"><h2>导入任务</h2><button type="button" className="btn secondary tiny" disabled={refreshing} onClick={()=>{void load()}}>{refreshing?'刷新中…':'刷新'}</button></div><table><thead><tr><th>类型</th><th>状态</th><th>提交状态</th><th>确认截止</th><th>摘要</th><th>时间</th><th>操作</th></tr></thead><tbody>{!jobs.length&&<tr><td colSpan="7" className="empty">暂无任务</td></tr>}{jobs.map(j=>{const state=jobState(j);return <tr key={j.id}><td>{j.kind||'—'}</td><td><Badge tone={stateTone(state)}>{stateLabel(state)}</Badge></td><td>{j.commit_state||j.business_state||'—'}</td><td>{date(j.confirm_expires_at)}</td><td>{importSummary(j)}</td><td>{date(j.created_at||j.updated_at)}</td><td>{renderActions(j)}</td></tr>})}</tbody></table></section><section className="card"><div className="card-head"><h2>导出任务</h2><div><select aria-label="导出数据类型" value={kind} onChange={e=>setKind(e.target.value)}><option value="category">分类</option><option value="part">零件</option><option value="bom">BOM</option></select> <select aria-label="导出格式" value={format} onChange={e=>setFormat(e.target.value)}><option value="csv">CSV</option><option value="json">JSON</option></select> {canExport&&<button type="button" className="btn secondary tiny" disabled={refreshing} onClick={()=>{void createExport()}}>创建导出</button>}</div></div><table><thead><tr><th>类型</th><th>格式</th><th>状态</th><th>时间</th><th>操作</th></tr></thead><tbody>{!exports.length&&<tr><td colSpan="5" className="empty">暂无导出</td></tr>}{exports.map(j=>{const state=jobState(j);return <tr key={j.id}><td>{j.kind||'—'}</td><td>{j.format||'—'}</td><td><Badge tone={stateTone(state)}>{stateLabel(state)}</Badge></td><td>{date(j.created_at||j.updated_at)}</td><td>{state==='completed'&&<button type="button" className="row-action" onClick={()=>{void downloadArtifact(j)}}>下载</button>}{renderActions(j)}</td></tr>})}</tbody></table></section></div>}
