import React,{useEffect,useState} from 'react'; import {apiRequest,endpoints} from './api.js'; import {PageHead,ErrorBox,Badge,Field,list} from './ui.jsx';
const states={draft:'草稿',pending_review:'待审核',rejected:'已驳回',approved:'已批准',release_pending:'待发布',release_failed:'发布失败',released:'已发布',obsolete:'已废止'};
export function LegacyPartsPage({navigate,openPart,reviewOnly=false,user}){const canWrite=["engineer","admin"].includes(user?.role);const [rows,setRows]=useState([]),[error,setError]=useState(null),[q,setQ]=useState('');const load=()=>apiRequest(`${endpoints.parts}${q?`?q=${encodeURIComponent(q)}`:''}`).then(x=>setRows(list(x))).catch(setError);useEffect(()=>{load()},[]);return <div className="page"><PageHead eyebrow="PLM" title={reviewOnly?'审核中心':'物料与零件'} desc="检索零件及 Revision 状态"/><form className="toolbar" onSubmit={e=>{e.preventDefault();load()}}><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索零件号或名称"/><button className="btn primary">查询</button>{!reviewOnly&&canWrite&&<button type="button" className="btn secondary" onClick={()=>navigate('new')}>新建零件</button>}</form><ErrorBox error={error}/><section className="card"><table><thead><tr><th>零件号</th><th>名称</th><th>Revision</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{rows.map(p=>{const r=(p.revisions||[]).slice(-1)[0]||p;return <tr key={p.id}><td className="part-number mono">{p.part_code}</td><td>{r.name||'—'}</td><td>{r.revision||'—'}</td><td><Badge tone={r.revision_state==='released'?'green':'blue'}>{states[r.revision_state]||r.revision_state||'—'}</Badge></td><td>{p.updated_at?new Date(p.updated_at).toLocaleString('zh-CN'):'—'}</td><td><button className="row-action" onClick={()=>openPart(p)}>查看</button></td></tr>})}{!rows.length&&<tr><td colSpan="6" className="empty">暂无数据</td></tr>}</tbody></table></section></div>}
export function PartsPage({navigate,openPart,reviewOnly=false,user}){
 const role=user?.role;const [rows,setRows]=useState([]),[error,setError]=useState(null),[q,setQ]=useState('');
 const reviewRole=role==='publisher'?'publisher':'reviewer';
 const load=async()=>{try{const payload=reviewOnly?await apiRequest(`${endpoints.reviewTasks}?role=${reviewRole}`):await apiRequest(`${endpoints.parts}${q?`?q=${encodeURIComponent(q)}`:''}`);setRows(Array.isArray(payload?.tasks)?payload.tasks:list(payload))}catch(e){setError(e)}};useEffect(()=>{void load()},[reviewOnly,role]);
 return <div className="page"><PageHead eyebrow="PLM" title={reviewOnly?'审核中心':'物料与零件'} desc={reviewOnly?'按当前角色筛选 review-tasks':'检索零件及 Revision 状态'}/><form className="toolbar" onSubmit={e=>{e.preventDefault();void load()}}>{!reviewOnly&&<input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索零件号或名称"/>}<button className="btn primary">查询</button>{!reviewOnly&&['engineer','admin'].includes(role)&&<button type="button" className="btn secondary" onClick={()=>navigate('new')}>新建零件</button>}</form><ErrorBox error={error}/><section className="card"><table><thead><tr><th>零件号</th><th>名称</th><th>Revision</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map((p,i)=>{const part=p.part||{...p,id:p.part_id||p.part?.id};const r=p.revision||((part.revisions||[]).slice(-1)[0]||part);return <tr key={p.id||i}><td className="part-number mono">{part.part_code||p.part_code||'—'}</td><td>{r.name||'—'}</td><td>{r.revision||'—'}</td><td><Badge tone={r.revision_state==='released'?'green':'blue'}>{states[r.revision_state]||r.revision_state||'—'}</Badge></td><td><button className="row-action" onClick={()=>openPart({...part,selected_revision_id:p.id})}>查看</button></td></tr>})}{!rows.length&&<tr><td colSpan="5" className="empty">暂无数据</td></tr>}</tbody></table></section></div>}export function WorkbenchPage({navigate,openPart,user}){
  const [parts,setParts]=useState([]),[boms,setBoms]=useState([]),[activity,setActivity]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null);
  useEffect(()=>{let alive=true;
    const canAudit=['admin','reviewer','publisher','auditor','sysadmin'].includes(user?.role);
    const requests=[apiRequest(endpoints.parts),apiRequest(endpoints.boms),canAudit?apiRequest(`${endpoints.audit}?limit=6`):Promise.resolve([])];
    Promise.allSettled(requests).then(([p,b,a])=>{
      if(!alive)return;
      setParts(p.status==='fulfilled'?list(p.value):[]); setBoms(b.status==='fulfilled'?list(b.value):[]); setActivity(a.status==='fulfilled'?list(a.value):[]);
      const failures=[p,b,a].filter(x=>x.status==='rejected'); if(failures.length)setError(failures[0].reason);
    }).finally(()=>alive&&setLoading(false)); return()=>{alive=false};
  },[user?.role]);
  const canWrite=["engineer","admin"].includes(user?.role);
  const revisions=parts.flatMap(p=>(p.revisions||[]).map(r=>({...r,part:p})));
  const recent=revisions.sort((a,b)=>new Date(b.updated_at||b.created_at||0)-new Date(a.updated_at||a.created_at||0)).slice(0,6);
  const pending=revisions.filter(r=>['pending_review','release_pending','release_failed'].includes(r.revision_state));
  const stat=(icon,tone,label,value,hint)=><article className="stat"><span className={`stat-icon ${tone}`}>{icon}</span><div><div className="stat-label">{label}</div><div className="stat-value">{loading?'—':value}</div><div className="stat-hint">{hint}</div></div></article>;
  return <div className="page">
    <PageHead eyebrow="PLM 工作台" title="工作台" desc={`欢迎回来，${user?.display_name||user?.username||'研发成员'}。查看研发数据概览、待办事项和最近变更。`}/>
    <ErrorBox error={error}/>
    <section className="stats">{stat('▦','blue','物料总数',parts.length,'进入物料与零件查看明细')}{stat('⌘','purple','BOM 总数',boms.length,'维护产品结构和 Revision')}{stat('!','amber','待处理事项',pending.length,'审核或发布流程需要关注')}{stat('✓','green','已发布 Revision',revisions.filter(r=>r.revision_state==='released').length,'已发布版本总数')}</section>
    <section className="grid-2">
      <article className="card"><div className="card-head"><div><h2>待办事项</h2><p className="muted">需要你关注的流程节点。</p></div><button className="btn ghost tiny" onClick={()=>navigate('approvals')}>审核中心</button></div><div className="todo-list">
        {!loading&&!pending.length&&<div className="empty">暂无待办事项</div>}
        {pending.slice(0,5).map(r=><button className="todo" key={r.id} onClick={()=>openPart(r.part)}><span className={`todo-icon ${r.revision_state==='release_failed'?'red':'amber'}`}>{r.revision_state==='release_failed'?'!':'◷'}</span><span><b>{r.part.part_code||'—'} · Revision {r.revision||'—'}</b><span>{states[r.revision_state]||r.revision_state||'待处理'}</span></span><strong>›</strong></button>)}
      </div></article>
      <article className="card activity"><div className="card-head"><div><h2>最近活动</h2><p className="muted">系统中最近发生的变更。</p></div><button className="btn ghost tiny" onClick={()=>navigate('audit')}>查看审计</button></div><div className="timeline">
        {!loading&&!activity.length&&<div className="empty">暂无活动记录</div>}
        {activity.slice(0,5).map((r,i)=><div className="activity-row" key={r.id||i}><span className="avatar">{(r.actor||'系').slice(0,1).toUpperCase()}</span><div><span><strong>{r.actor||'系统'}</strong> {r.action||'更新资源'}</span><small>{r.resource_type||'资源'} {r.resource_id||''} · {r.created_at?new Date(r.created_at).toLocaleString('zh-CN'):'—'}</small></div></div>)}
      </div></article>
    </section>
    <section className="card"><div className="card-head"><div><h2>快捷操作</h2><p className="muted">从这里开始常用 PLM/BOM 工作。</p></div></div><div className="toolbar">{canWrite&&<button className="btn primary" onClick={()=>navigate('new')}>新建零件</button>}<button className="btn secondary" onClick={()=>navigate('parts')}>检索物料</button><button className="btn secondary" onClick={()=>navigate('boms')}>查看 BOM</button><button className="btn secondary" onClick={()=>navigate('jobs')}>导入导出</button></div></section>
    <section className="card"><div className="card-head"><div><h2>最近 Revision</h2><p className="muted">最近更新的物料版本和当前状态。</p></div><button className="btn ghost tiny" onClick={()=>navigate('parts')}>查看全部</button></div><div className="table-wrap"><table><thead><tr><th>零件号</th><th>名称</th><th>Revision</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{!loading&&!recent.length&&<tr><td colSpan="6" className="empty">暂无 Revision</td></tr>}{recent.map(r=><tr key={r.id}><td className="part-number mono">{r.part.part_code||'—'}</td><td>{r.name||'—'}</td><td>{r.revision||'—'}</td><td><Badge tone={r.revision_state==='released'?'green':r.revision_state==='release_failed'?'red':'blue'}>{states[r.revision_state]||r.revision_state||'—'}</Badge></td><td>{r.updated_at?new Date(r.updated_at).toLocaleString('zh-CN'):'—'}</td><td><button className="row-action" onClick={()=>openPart(r.part)}>查看</button></td></tr>)}</tbody></table></div></section>
  </div>
}
