import React,{useEffect,useState} from 'react';
import {apiRequest} from './api.js';
import {Badge,ErrorBox,PageHead,uploadAttachment,list} from './ui.jsx';
const dt=x=>x?new Date(x).toLocaleString('zh-CN'):'—';
const states={draft:'草稿',pending_review:'待审核',rejected:'已驳回',approved:'已批准',release_pending:'待发布',release_failed:'发布失败',released:'已发布',obsolete:'已废止'};
const attachmentState={scanning:'扫描中',pending:'待扫描',available:'可用',opaque:'加密可用',quarantined:'已隔离',error:'扫描错误'};
export function PartDetailPage({partId,navigate}){
 const [part,setPart]=useState(null),[events,setEvents]=useState([]),[attachments,setAttachments]=useState([]),[tab,setTab]=useState('overview'),[error,setError]=useState(null),[busy,setBusy]=useState(false),[attachment,setAttachment]=useState(null),[progress,setProgress]=useState(0),[uploading,setUploading]=useState(false),[encryptionMode,setEncryptionMode]=useState('none'),[compareId,setCompareId]=useState('');
 const load=async()=>{setError(null);try{const [p,t]=await Promise.all([apiRequest(`/parts/${partId}`),apiRequest(`/parts/${partId}/timeline`)]);setPart(p);setEvents(list(t));const rev=[...(p?.revisions||[])].sort((a,b)=>(b.revision_seq||0)-(a.revision_seq||0))[0];if(rev?.id){const a=await apiRequest(`/parts/${partId}/attachments?revision=${encodeURIComponent(rev.id)}`);setAttachments(list(a))}}catch(e){setError(e)}};
 useEffect(()=>{void load()},[partId]);
 const revs=part?.revisions||[],latest=[...revs].sort((a,b)=>(b.revision_seq||0)-(a.revision_seq||0))[0],canAction=action=>Array.isArray(latest?.allowed_actions)&&latest.allowed_actions.includes(action),compareRevision=revs.find(r=>String(r.id)===String(compareId));
 const transition=async action=>{if(!latest||!canAction(action))return;let reason='';if(['reject','withdraw'].includes(action)){reason=window.prompt(action==='reject'?'请输入驳回原因':'请输入撤回原因')||'';if(!reason)return}setBusy(true);try{await apiRequest(`/parts/${partId}/revisions/${latest.id}/actions`,{method:'POST',body:{action,reason},rowVersion:latest.row_version,idempotencyKey:crypto.randomUUID()});await load()}catch(e){setError(e)}finally{setBusy(false)}};
 const attach=async()=>{if(!attachment||!latest)return;setUploading(true);try{const s=await uploadAttachment(attachment,setProgress);await apiRequest(`/parts/${partId}/attachments`,{method:'POST',body:{revision:latest.id,upload_session:s.id,encryption_mode:encryptionMode},rowVersion:latest.row_version,idempotencyKey:crypto.randomUUID()});setAttachment(null);await load()}catch(e){setError(e)}finally{setUploading(false)}};
 const downloadAttachment=async(version,mode,attachmentId)=>{try{const body={mode};if(mode==='draft')body.link_id=attachmentId||version.link_id;else body.release_publication_id=latest?.publication_id;if(mode==='historical')body.as_of=new Date().toISOString();const r=await apiRequest(`/attachment-versions/${version.id}/download`,{method:'POST',body,idempotencyKey:crypto.randomUUID()});if(r.download_license)window.open(`/api/v1/attachment-versions/${version.id}/content?download_license=${encodeURIComponent(r.download_license)}`,'_blank','noopener,noreferrer')}catch(e){setError(e)}};
 if(!part&&!error)return <div className="page"><div className="empty-panel card">加载中…</div></div>;
 return <div className="page"><PageHead eyebrow="物料主数据 · 详情" title={<span className="part-number">{part?.part_code||'物料详情'}</span>} desc={latest?.name||'—'}/>
  <div className="toolbar"><button className="btn secondary" onClick={()=>navigate('parts')}>返回列表</button>{latest?.revision_state==='draft'&&canAction('submit')&&<button className="btn primary" disabled={busy} onClick={()=>transition('submit')}>提交审核</button>}{latest?.revision_state==='pending_review'&&canAction('approve')&&<><button className="btn primary" disabled={busy} onClick={()=>transition('approve')}>批准</button><button className="btn secondary" disabled={busy} onClick={()=>transition('reject')}>驳回</button></>}{latest?.revision_state==='pending_review'&&canAction('withdraw')&&<button className="btn secondary" disabled={busy} onClick={()=>transition('withdraw')}>撤回</button>}{latest?.revision_state==='rejected'&&canAction('revise')&&<button className="btn primary" disabled={busy} onClick={()=>transition('revise')}>重新编辑</button>}{latest?.revision_state==='approved'&&canAction('publish')&&<button className="btn primary" disabled={busy} onClick={()=>transition('publish')}>申请发布</button>}{latest?.revision_state==='release_pending'&&canAction('release')&&<button className="btn primary" disabled={busy} onClick={()=>transition('release')}>发布</button>}{latest?.revision_state==='release_failed'&&canAction('retry_publish')&&<button className="btn primary" disabled={busy} onClick={()=>transition('retry_publish')}>重试发布</button>}{latest?.revision_state==='release_failed'&&canAction('abandon_publish')&&<button className="btn secondary" disabled={busy} onClick={()=>transition('abandon_publish')}>放弃发布</button>}{latest?.revision_state==='released'&&canAction('retire')&&<button className="btn secondary" disabled={busy} onClick={()=>transition('retire')}>废止</button>}</div><ErrorBox error={error}/>
  <div className="tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>主数据</button><button className={tab==='revisions'?'active':''} onClick={()=>setTab('revisions')}>Revision ({revs.length})</button><button className={tab==='timeline'?'active':''} onClick={()=>setTab('timeline')}>时间线</button><button className={tab==='compare'?'active':''} onClick={()=>setTab('compare')}>版本对比</button><button className={tab==='attachments'?'active':''} onClick={()=>setTab('attachments')}>图纸与附件 ({attachments.length})</button></div>
  {tab==='overview'&&<section className="card"><div className="detail-grid">{[['状态',part?.status],['Revision',latest?.revision],['类型',latest?.kind],['生命周期',latest?.business_lifecycle],['标准号',latest?.standard_code],['材料',latest?.material],['制造商',latest?.manufacturer],['制造商料号',latest?.manufacturer_part_number],['RoHS',latest?.rohs_standard],['单位',latest?.unit_code]].map(([k,v])=><div key={k}><span className="muted">{k}</span><b>{v||'—'}</b></div>)}</div><p>{latest?.description||'暂无描述'}</p></section>}
  {tab==='revisions'&&<section className="card"><table><thead><tr><th>Revision</th><th>状态</th><th>生命周期</th><th>附件</th><th>创建时间</th></tr></thead><tbody>{revs.map(r=><tr key={r.id}><td className="mono strong">{r.revision}</td><td><Badge tone={r.revision_state==='released'?'green':r.revision_state==='rejected'?'red':'blue'}>{states[r.revision_state]||r.revision_state}</Badge></td><td>{r.business_lifecycle||'—'}</td><td>{r.attachment_count||0}</td><td>{dt(r.created_at)}</td></tr>)}</tbody></table></section>}
  {tab==='compare'&&<section className="card"><label className="field"><span>选择对比 Revision</span><select value={compareId} onChange={e=>setCompareId(e.target.value)}><option value="">请选择版本</option>{revs.filter(r=>r.id!==latest?.id).map(r=><option key={r.id} value={r.id}>{r.revision} · {states[r.revision_state]||r.revision_state}</option>)}</select></label>{compareRevision?<div className="revision-diff">{['name','kind','business_lifecycle','standard_code','material','manufacturer','manufacturer_part_number','rohs_standard','description'].map(key=>{const a=latest?.[key]??'',b=compareRevision?.[key]??'';return <div className={String(a)!==String(b)?'diff-row changed':'diff-row'} key={key}><span>{key}</span><code>{b||'—'}</code><b>→</b><code>{a||'—'}</code></div>})}</div>:<div className="empty">选择历史版本查看字段差异</div>}</section>}
  {tab==='timeline'&&<section className="card timeline">{events.map((e,i)=><div className="timeline-item" key={e.id||i}><b>{e.action||'操作'}</b><span>{e.actor||'系统'} · {dt(e.created_at)}</span><p>{e.details?JSON.stringify(e.details):''}</p></div>)}{!events.length&&<div className="empty">暂无审计事件</div>}</section>}
  {tab==='attachments'&&<section className="card"><h2>图纸与附件</h2><p className="muted">附件状态由扫描 Worker 和发布屏障决定；下载前必须获取短期授权许可。</p>{latest?.revision_state==='draft'&&<div className="form-actions"><input type="file" onChange={e=>setAttachment(e.target.files?.[0]||null)} disabled={uploading}/><select value={encryptionMode} onChange={e=>setEncryptionMode(e.target.value)} disabled={uploading}><option value="none">明文（ClamAV 扫描）</option><option value="transparent">透明加密</option></select><button className="btn primary" disabled={!attachment||uploading} onClick={()=>void attach()}>{uploading?`上传 ${progress}%`:'上传并绑定'}</button></div>}<div className="file-list">{attachments.map(a=><div className="file-row" key={a.id}><div className="file-name"><b>{a.filename||'未命名附件'}</b><span>{a.versions?.length||0} 个版本 · {a.encryption_mode||'none'}</span></div>{(a.versions||[]).map(v=><React.Fragment key={v.id}><Badge tone={v.security_state==='available'||v.security_state==='opaque'?'green':v.security_state==='quarantined'?'red':'amber'}>{attachmentState[v.security_state]||v.security_state}</Badge>{(v.security_state==='available'||v.security_state==='opaque')&&<><button className="row-action" onClick={()=>void downloadAttachment(v,'draft',a.id)}>草稿下载</button>{latest?.publication_id&&<button className="row-action" onClick={()=>void downloadAttachment(v,'current')}>当前下载</button>}<button className="row-action" onClick={()=>void downloadAttachment(v,'historical')}>历史下载</button></>}</React.Fragment>)}</div>)}{!attachments.length&&<div className="empty">暂无附件</div>}</div></section>}
 </div>;
}
