import React,{useEffect,useState} from 'react';
import {apiRequest} from './api.js';
import {sessionNeedsRecreate,serverPartMap,finalizeJobPending} from './upload-contract.js';
export {apiRequest};
export const list=x=>Array.isArray(x?.results)?x.results:Array.isArray(x)?x:[];
export function Field({label,children,wide=false}){return <label className={wide?'field wide':'field'}><span>{label}</span>{children}</label>}
export function ErrorBox({error}){if(!error)return null;const retry=error?.retryAfter?`（建议 ${error.retryAfter} 秒后重试）`:'';const meta=[error?.code,error?.requestId&&`request_id: ${error.requestId}`].filter(Boolean).join(' · ');return <div className="error-banner" role="alert">{error?.message||String(error)}{meta&&<small className="error-meta"> [{meta}]</small>}{retry}</div>}
export function Badge({children,tone='gray'}){return <span className={'badge '+tone}><i/>{children}</span>}
export function PageHead({eyebrow,title,desc}){return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div></div>}
export function useData(path,refresh=0){const[data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null),[reload,setReload]=useState(0);useEffect(()=>{let alive=true;setLoading(true);setError(null);apiRequest(path).then(x=>alive&&setData(x)).catch(x=>alive&&setError(x)).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[path,refresh,reload]);return {data,loading,error,refresh:()=>setReload(v=>v+1)}}
export const MAX_ATTACHMENT_BYTES=5*1024**3,MAX_IMPORT_BYTES=5*1024**2,UPLOAD_PART_BYTES=64*1024**2;
const sessionKey=f=>`partflow.upload.${f.name}.${f.size}.${f.lastModified}`;
export async function probeUploadCapabilities(){if(!(window.isSecureContext||['localhost','127.0.0.1','[::1]'].includes(location.hostname)))throw Error('当前环境不支持安全上传，请使用 HTTPS 或 localhost');if(!globalThis.crypto?.subtle)throw Error('当前浏览器缺少 crypto.subtle，无法计算校验和');if(typeof AbortController==='undefined'||typeof fetch!=='function')throw Error('当前浏览器不支持可取消上传请求');if(typeof File==='undefined'||typeof File.prototype.slice!=='function')throw Error('当前浏览器不支持分片上传')}
// WebCrypto's digest() requires the complete input in memory.  This small
// incremental implementation keeps only one 4 MiB slice plus the SHA-256
// state, so selecting a multi-GiB attachment does not allocate a multi-GiB
// ArrayBuffer in the browser.
class Sha256 {
 constructor(){this.h=new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]);this.buf=new Uint8Array(64);this.len=0;this.n=0}
 update(data){for(let i=0;i<data.length;i++){this.buf[this.n++]=data[i];this.len++;if(this.n===64){this.block(this.buf);this.n=0}}return this}
 block(b){const k=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];const w=new Uint32Array(64);for(let i=0;i<16;i++)w[i]=((b[i*4]<<24)|(b[i*4+1]<<16)|(b[i*4+2]<<8)|b[i*4+3])>>>0;for(let i=16;i<64;i++){const x=w[i-15],y=w[i-2],s0=((x>>>7)|(x<<25))^((x>>>18)|(x<<14))^(x>>>3),s1=((y>>>17)|(y<<15))^((y>>>19)|(y<<13))^(y>>>10);w[i]=(w[i-16]+s0+w[i-7]+s1)>>>0}let [a,bb,c,d,e,f,g,h]=this.h;for(let i=0;i<64;i++){const S1=((e>>>6)|(e<<26))^((e>>>11)|(e<<21))^((e>>>25)|(e<<7)),ch=(e&f)^(~e&g),t1=(h+S1+ch+k[i]+w[i])>>>0,S0=((a>>>2)|(a<<30))^((a>>>13)|(a<<19))^((a>>>22)|(a<<10)),maj=(a&bb)^(a&c)^(bb&c),t2=(S0+maj)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=bb;bb=a;a=(t1+t2)>>>0}this.h[0]=(this.h[0]+a)>>>0;this.h[1]=(this.h[1]+bb)>>>0;this.h[2]=(this.h[2]+c)>>>0;this.h[3]=(this.h[3]+d)>>>0;this.h[4]=(this.h[4]+e)>>>0;this.h[5]=(this.h[5]+f)>>>0;this.h[6]=(this.h[6]+g)>>>0;this.h[7]=(this.h[7]+h)>>>0}
 digest(){const bitLen=this.len*8;this.update(new Uint8Array([0x80]));while(this.n!==56)this.update(new Uint8Array([0]));const tail=new Uint8Array(8);for(let i=0;i<8;i++)tail[7-i]=Math.floor(bitLen/2**(i*8))&255;this.update(tail);return [...this.h].map(x=>x.toString(16).padStart(8,'0')).join('')}
}
export async function sha256File(file){const hash=new Sha256(),chunk=4*1024*1024;for(let offset=0;offset<file.size;offset+=chunk)hash.update(new Uint8Array(await file.slice(offset,Math.min(file.size,offset+chunk)).arrayBuffer()));return hash.digest()}
async function presignBatch(id,numbers){const r=await apiRequest(`/attachments/upload-sessions/${id}/parts/presign`,{method:'POST',body:{part_numbers:numbers}});return r.parts||r.part_urls||r}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function putPart(url,body,headers,onRetry){let current=url;for(let attempt=0;attempt<3;attempt++){const r=await fetch(current,{method:'PUT',mode:'cors',body,headers,signal:(new AbortController()).signal});if(r.ok)return r;const retry=Number(r.headers.get('Retry-After')||0);if((r.status===403||r.status===404)&&onRetry){const refreshed=await onRetry();if(refreshed){current=refreshed;continue}}if(![408,425,429,500,502,503,504].includes(r.status)||attempt===2){const e=new Error(`分片上传失败（HTTP ${r.status}）`);if(retry>0)e.retryAfter=retry;throw e}await wait(Math.min(30000,(retry>0?retry*1000:500*2**attempt)))}throw Error('分片上传失败')}
export async function uploadFile(file,onProgress=()=>{},maxBytes=MAX_IMPORT_BYTES,purpose='import_source'){
 if(!file||file.size<=0)throw Error('请选择非空文件'); if(file.size>maxBytes)throw Error(maxBytes>=MAX_ATTACHMENT_BYTES?'附件不能超过 5 GiB':'结构化导入文件不能超过 5 MiB'); await probeUploadCapabilities();
 const digest=await sha256File(file),key=sessionKey(file);let saved=null;try{saved=JSON.parse(localStorage.getItem(key)||'null')}catch{}
 const same=saved&&saved.name===file.name&&saved.size===file.size&&saved.lastModified===file.lastModified; let s=null; if(same&&saved.id){try{s=await apiRequest(`/attachments/upload-sessions/${saved.id}`)}catch(e){if(e?.status!==404)throw e}}
 if(sessionNeedsRecreate(s)){s=await apiRequest('/attachments/upload-sessions',{method:'POST',body:{filename:file.name,size:file.size,content_type:file.type||'application/octet-stream',purpose,part_size:UPLOAD_PART_BYTES,total_chunks:Math.ceil(file.size/UPLOAD_PART_BYTES),sha256:digest}});localStorage.setItem(key,JSON.stringify({id:s.id,name:file.name,size:file.size,lastModified:file.lastModified,part_size:s.part_size||UPLOAD_PART_BYTES}))}
 if(['uploaded','verified'].includes(String(s.state||'').toLowerCase())){localStorage.removeItem(key);return s}
 const partSize=Number(s.part_size||UPLOAD_PART_BYTES); const total=s.total_chunks||Math.ceil(file.size/partSize); const receipt=await apiRequest(`/attachments/upload-sessions/${s.id}/parts`); const done=serverPartMap(receipt),urls=s.part_urls||[];
 for(let start=1;start<=total;start+=20){const nums=Array.from({length:Math.min(20,total-start+1)},(_,i)=>start+i).filter(n=>!done.has(n));if(!nums.length)continue;let batch=urls.length?nums.map(n=>urls[n-1]):await presignBatch(s.id,nums);for(let i=0;i<nums.length;i++){const n=nums[i],body=file.slice((n-1)*partSize,Math.min(file.size,n*partSize)),checksum=await sha256File(body);let entry=typeof batch[i]==='string'?{url:batch[i]}:batch[i],url=entry.url||entry.presigned_url;if(!url)throw Error('上传分片地址缺失');const r=await putPart(url,body,entry.headers||{},async()=>{const fresh=await presignBatch(s.id,[n]);entry=typeof fresh[0]==='string'?{url:fresh[0]}:fresh[0];return entry.url||entry.presigned_url});const etag=r.headers.get('ETag')||r.headers.get('etag');if(!etag)throw Error('MinIO 未返回 ETag，请检查桶的跨域配置');const part={part_number:n,etag:etag.replaceAll('"',''),size:body.size,checksum_sha256:checksum};done.set(n,part);localStorage.setItem(key,JSON.stringify({id:s.id,name:file.name,size:file.size,lastModified:file.lastModified,part_size:partSize,parts:[...done.values()]}));onProgress(Math.round(done.size/total*100))}}
 const result=await apiRequest(`/attachments/upload-sessions/${s.id}/actions`,{method:'POST',body:{action:'finalize',part_size:partSize,parts:[...done.values()].sort((a,b)=>a.part_number-b.part_number)},rowVersion:s.generation});
 if(finalizeJobPending(result)){for(let attempt=0;attempt<120;attempt++){await wait(1000);const job=await apiRequest(`/jobs/${result.job_id}`);if((job.status||job.execution_state)==='completed'){const fresh=await apiRequest(`/attachments/upload-sessions/${s.id}`);localStorage.removeItem(key);return fresh}if(['failed','cancelled'].includes(job.status||job.execution_state)){const e=new Error(job.error||'上传提交失败');e.code='UPLOAD_FINALIZE_FAILED';throw e}}const e=new Error('上传提交超时');e.code='UPLOAD_FINALIZE_TIMEOUT';throw e}
 localStorage.removeItem(key);return result;
}
export const uploadAttachment=(file,onProgress,purpose='part_attachment')=>uploadFile(file,onProgress,MAX_ATTACHMENT_BYTES,purpose);


